
spring:
  application:
    name:Shop
  datasource:
    url: jdbc:postgresql://localhost:5432/g_33_shop
    username: postgres
    password: Amigo1997!!!
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true


key:
  access: 1cCFThHQ2hvK2rOym9SGAHCRwyh4CVCufUnA0NX7xuk=
  refresh: etOhb8orqmjBAXkEVRw7b5l1x0TRZNj9wmL8QsyDFn8=

messages:
  hello: Hello from local application!
